### ISSUE TITLE
Publish the sourcecode

### ISSUE THREAD

**Issue by v1nc** [TheWCKD/CoronaVirus-Outbreak-App#2]
Please publish your sourcecode on github!
Why are you using github at all?

**Comment by c33s** [comment]
also publish the app apk on githubs releases page

**Comment by TheWCKD** [comment]
I won't publish any sourcecode, the project is closed source. I'm using github just for the updates present in readme file. The reason I'm not posting any sourcecode because there are a lot of scammers in this period trying to steal and modify project so that they can profit from them. If you don't trust the app, don't use it, simple as that. Will consider posting the latest version into github releases page. Closed.
